/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ScenariosRouteRouteImport } from "./routes/scenarios/route";
import { Route as SettingsRouteRouteImport } from "./routes/settings/route";
import { Route as CampaignsCampaignIdRouteImport } from "./routes/campaigns/$campaignId";
import { Route as ScenariosIndexRouteImport } from "./routes/scenarios/index";
import { Route as ScenariosScenarioIdRouteImport } from "./routes/scenarios/$scenarioId";
import { Route as SettingsGeneralRouteImport } from "./routes/settings/general";
import { Route as SettingsStorageRouteImport } from "./routes/settings/storage";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ScenariosRouteRoute = ScenariosRouteRouteImport.update({
  id: "/scenarios",
  path: "/scenarios",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: "/campaigns/$campaignId",
  path: "/campaigns/$campaignId",
  getParentRoute: () => rootRouteImport,
} as any);
const ScenariosIndexRoute = ScenariosIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ScenariosRouteRoute,
} as any);
const ScenariosScenarioIdRoute = ScenariosScenarioIdRouteImport.update({
  id: "/$scenarioId",
  path: "/$scenarioId",
  getParentRoute: () => ScenariosRouteRoute,
} as any);
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: "/general",
  path: "/general",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: "/storage",
  path: "/storage",
  getParentRoute: () => SettingsRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/scenarios": typeof ScenariosRouteRouteWithChildren;
  "/settings": typeof SettingsRouteRouteWithChildren;
  "/campaigns/$campaignId": typeof CampaignsCampaignIdRoute;
  "/scenarios/$scenarioId": typeof ScenariosScenarioIdRoute;
  "/settings/general": typeof SettingsGeneralRoute;
  "/settings/storage": typeof SettingsStorageRoute;
  "/scenarios/": typeof ScenariosIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRouteRouteWithChildren;
  "/campaigns/$campaignId": typeof CampaignsCampaignIdRoute;
  "/scenarios/$scenarioId": typeof ScenariosScenarioIdRoute;
  "/settings/general": typeof SettingsGeneralRoute;
  "/settings/storage": typeof SettingsStorageRoute;
  "/scenarios": typeof ScenariosIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/scenarios": typeof ScenariosRouteRouteWithChildren;
  "/settings": typeof SettingsRouteRouteWithChildren;
  "/campaigns/$campaignId": typeof CampaignsCampaignIdRoute;
  "/scenarios/$scenarioId": typeof ScenariosScenarioIdRoute;
  "/settings/general": typeof SettingsGeneralRoute;
  "/settings/storage": typeof SettingsStorageRoute;
  "/scenarios/": typeof ScenariosIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/scenarios"
    | "/settings"
    | "/campaigns/$campaignId"
    | "/scenarios/$scenarioId"
    | "/settings/general"
    | "/settings/storage"
    | "/scenarios/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/settings"
    | "/campaigns/$campaignId"
    | "/scenarios/$scenarioId"
    | "/settings/general"
    | "/settings/storage"
    | "/scenarios";
  id:
    | "__root__"
    | "/"
    | "/scenarios"
    | "/settings"
    | "/campaigns/$campaignId"
    | "/scenarios/$scenarioId"
    | "/settings/general"
    | "/settings/storage"
    | "/scenarios/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ScenariosRouteRoute: typeof ScenariosRouteRouteWithChildren;
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren;
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/scenarios": {
      id: "/scenarios";
      path: "/scenarios";
      fullPath: "/scenarios";
      preLoaderRoute: typeof ScenariosRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/campaigns/$campaignId": {
      id: "/campaigns/$campaignId";
      path: "/campaigns/$campaignId";
      fullPath: "/campaigns/$campaignId";
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/scenarios/": {
      id: "/scenarios/";
      path: "/";
      fullPath: "/scenarios/";
      preLoaderRoute: typeof ScenariosIndexRouteImport;
      parentRoute: typeof ScenariosRouteRoute;
    };
    "/scenarios/$scenarioId": {
      id: "/scenarios/$scenarioId";
      path: "/$scenarioId";
      fullPath: "/scenarios/$scenarioId";
      preLoaderRoute: typeof ScenariosScenarioIdRouteImport;
      parentRoute: typeof ScenariosRouteRoute;
    };
    "/settings/general": {
      id: "/settings/general";
      path: "/general";
      fullPath: "/settings/general";
      preLoaderRoute: typeof SettingsGeneralRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/storage": {
      id: "/settings/storage";
      path: "/storage";
      fullPath: "/settings/storage";
      preLoaderRoute: typeof SettingsStorageRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
  }
}

interface ScenariosRouteRouteChildren {
  ScenariosScenarioIdRoute: typeof ScenariosScenarioIdRoute;
  ScenariosIndexRoute: typeof ScenariosIndexRoute;
}

const ScenariosRouteRouteChildren: ScenariosRouteRouteChildren = {
  ScenariosScenarioIdRoute: ScenariosScenarioIdRoute,
  ScenariosIndexRoute: ScenariosIndexRoute,
};

const ScenariosRouteRouteWithChildren = ScenariosRouteRoute._addFileChildren(
  ScenariosRouteRouteChildren,
);

interface SettingsRouteRouteChildren {
  SettingsGeneralRoute: typeof SettingsGeneralRoute;
  SettingsStorageRoute: typeof SettingsStorageRoute;
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsStorageRoute: SettingsStorageRoute,
};

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScenariosRouteRoute: ScenariosRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
