/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ScenariosRouteRouteImport } from "./routes/scenarios/route";
import { Route as SettingsRouteRouteImport } from "./routes/settings/route";
import { Route as CampaignsCampaignIdRouteImport } from "./routes/campaigns/$campaignId";
import { Route as ScenariosIndexRouteImport } from "./routes/scenarios/index";
import { Route as ScenariosScenarioIdRouteImport } from "./routes/scenarios/$scenarioId";
import { Route as ScenariosNewRouteImport } from "./routes/scenarios/new";
import { Route as SettingsAdvancedRouteImport } from "./routes/settings/advanced";
import { Route as SettingsAppearanceRouteImport } from "./routes/settings/appearance";
import { Route as SettingsGeneralRouteImport } from "./routes/settings/general";
import { Route as SettingsInstructionsRouteImport } from "./routes/settings/instructions";
import { Route as SettingsMarkdownEditorRouteImport } from "./routes/settings/markdown-editor";
import { Route as SettingsProvidersRouteImport } from "./routes/settings/providers";
import { Route as SettingsStorageRouteImport } from "./routes/settings/storage";
import { Route as SettingsUsageRouteImport } from "./routes/settings/usage";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ScenariosRouteRoute = ScenariosRouteRouteImport.update({
  id: "/scenarios",
  path: "/scenarios",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: "/campaigns/$campaignId",
  path: "/campaigns/$campaignId",
  getParentRoute: () => rootRouteImport,
} as any);
const ScenariosIndexRoute = ScenariosIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ScenariosRouteRoute,
} as any);
const ScenariosScenarioIdRoute = ScenariosScenarioIdRouteImport.update({
  id: "/$scenarioId",
  path: "/$scenarioId",
  getParentRoute: () => ScenariosRouteRoute,
} as any);
const ScenariosNewRoute = ScenariosNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => ScenariosRouteRoute,
} as any);
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: "/advanced",
  path: "/advanced",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: "/appearance",
  path: "/appearance",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: "/general",
  path: "/general",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsInstructionsRoute = SettingsInstructionsRouteImport.update({
  id: "/instructions",
  path: "/instructions",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsMarkdownEditorRoute = SettingsMarkdownEditorRouteImport.update({
  id: "/markdown-editor",
  path: "/markdown-editor",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: "/providers",
  path: "/providers",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: "/storage",
  path: "/storage",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsUsageRoute = SettingsUsageRouteImport.update({
  id: "/usage",
  path: "/usage",
  getParentRoute: () => SettingsRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/scenarios": typeof ScenariosRouteRouteWithChildren;
  "/settings": typeof SettingsRouteRouteWithChildren;
  "/campaigns/$campaignId": typeof CampaignsCampaignIdRoute;
  "/scenarios/$scenarioId": typeof ScenariosScenarioIdRoute;
  "/scenarios/new": typeof ScenariosNewRoute;
  "/settings/advanced": typeof SettingsAdvancedRoute;
  "/settings/appearance": typeof SettingsAppearanceRoute;
  "/settings/general": typeof SettingsGeneralRoute;
  "/settings/instructions": typeof SettingsInstructionsRoute;
  "/settings/markdown-editor": typeof SettingsMarkdownEditorRoute;
  "/settings/providers": typeof SettingsProvidersRoute;
  "/settings/storage": typeof SettingsStorageRoute;
  "/settings/usage": typeof SettingsUsageRoute;
  "/scenarios/": typeof ScenariosIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRouteRouteWithChildren;
  "/campaigns/$campaignId": typeof CampaignsCampaignIdRoute;
  "/scenarios/$scenarioId": typeof ScenariosScenarioIdRoute;
  "/scenarios/new": typeof ScenariosNewRoute;
  "/settings/advanced": typeof SettingsAdvancedRoute;
  "/settings/appearance": typeof SettingsAppearanceRoute;
  "/settings/general": typeof SettingsGeneralRoute;
  "/settings/instructions": typeof SettingsInstructionsRoute;
  "/settings/markdown-editor": typeof SettingsMarkdownEditorRoute;
  "/settings/providers": typeof SettingsProvidersRoute;
  "/settings/storage": typeof SettingsStorageRoute;
  "/settings/usage": typeof SettingsUsageRoute;
  "/scenarios": typeof ScenariosIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/scenarios": typeof ScenariosRouteRouteWithChildren;
  "/settings": typeof SettingsRouteRouteWithChildren;
  "/campaigns/$campaignId": typeof CampaignsCampaignIdRoute;
  "/scenarios/$scenarioId": typeof ScenariosScenarioIdRoute;
  "/scenarios/new": typeof ScenariosNewRoute;
  "/settings/advanced": typeof SettingsAdvancedRoute;
  "/settings/appearance": typeof SettingsAppearanceRoute;
  "/settings/general": typeof SettingsGeneralRoute;
  "/settings/instructions": typeof SettingsInstructionsRoute;
  "/settings/markdown-editor": typeof SettingsMarkdownEditorRoute;
  "/settings/providers": typeof SettingsProvidersRoute;
  "/settings/storage": typeof SettingsStorageRoute;
  "/settings/usage": typeof SettingsUsageRoute;
  "/scenarios/": typeof ScenariosIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/scenarios"
    | "/settings"
    | "/campaigns/$campaignId"
    | "/scenarios/$scenarioId"
    | "/scenarios/new"
    | "/settings/advanced"
    | "/settings/appearance"
    | "/settings/general"
    | "/settings/instructions"
    | "/settings/markdown-editor"
    | "/settings/providers"
    | "/settings/storage"
    | "/settings/usage"
    | "/scenarios/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/settings"
    | "/campaigns/$campaignId"
    | "/scenarios/$scenarioId"
    | "/scenarios/new"
    | "/settings/advanced"
    | "/settings/appearance"
    | "/settings/general"
    | "/settings/instructions"
    | "/settings/markdown-editor"
    | "/settings/providers"
    | "/settings/storage"
    | "/settings/usage"
    | "/scenarios";
  id:
    | "__root__"
    | "/"
    | "/scenarios"
    | "/settings"
    | "/campaigns/$campaignId"
    | "/scenarios/$scenarioId"
    | "/scenarios/new"
    | "/settings/advanced"
    | "/settings/appearance"
    | "/settings/general"
    | "/settings/instructions"
    | "/settings/markdown-editor"
    | "/settings/providers"
    | "/settings/storage"
    | "/settings/usage"
    | "/scenarios/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ScenariosRouteRoute: typeof ScenariosRouteRouteWithChildren;
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren;
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/scenarios": {
      id: "/scenarios";
      path: "/scenarios";
      fullPath: "/scenarios";
      preLoaderRoute: typeof ScenariosRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/campaigns/$campaignId": {
      id: "/campaigns/$campaignId";
      path: "/campaigns/$campaignId";
      fullPath: "/campaigns/$campaignId";
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/scenarios/": {
      id: "/scenarios/";
      path: "/";
      fullPath: "/scenarios/";
      preLoaderRoute: typeof ScenariosIndexRouteImport;
      parentRoute: typeof ScenariosRouteRoute;
    };
    "/scenarios/$scenarioId": {
      id: "/scenarios/$scenarioId";
      path: "/$scenarioId";
      fullPath: "/scenarios/$scenarioId";
      preLoaderRoute: typeof ScenariosScenarioIdRouteImport;
      parentRoute: typeof ScenariosRouteRoute;
    };
    "/scenarios/new": {
      id: "/scenarios/new";
      path: "/new";
      fullPath: "/scenarios/new";
      preLoaderRoute: typeof ScenariosNewRouteImport;
      parentRoute: typeof ScenariosRouteRoute;
    };
    "/settings/advanced": {
      id: "/settings/advanced";
      path: "/advanced";
      fullPath: "/settings/advanced";
      preLoaderRoute: typeof SettingsAdvancedRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/appearance": {
      id: "/settings/appearance";
      path: "/appearance";
      fullPath: "/settings/appearance";
      preLoaderRoute: typeof SettingsAppearanceRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/general": {
      id: "/settings/general";
      path: "/general";
      fullPath: "/settings/general";
      preLoaderRoute: typeof SettingsGeneralRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/instructions": {
      id: "/settings/instructions";
      path: "/instructions";
      fullPath: "/settings/instructions";
      preLoaderRoute: typeof SettingsInstructionsRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/markdown-editor": {
      id: "/settings/markdown-editor";
      path: "/markdown-editor";
      fullPath: "/settings/markdown-editor";
      preLoaderRoute: typeof SettingsMarkdownEditorRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/providers": {
      id: "/settings/providers";
      path: "/providers";
      fullPath: "/settings/providers";
      preLoaderRoute: typeof SettingsProvidersRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/storage": {
      id: "/settings/storage";
      path: "/storage";
      fullPath: "/settings/storage";
      preLoaderRoute: typeof SettingsStorageRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/usage": {
      id: "/settings/usage";
      path: "/usage";
      fullPath: "/settings/usage";
      preLoaderRoute: typeof SettingsUsageRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
  }
}

interface ScenariosRouteRouteChildren {
  ScenariosScenarioIdRoute: typeof ScenariosScenarioIdRoute;
  ScenariosNewRoute: typeof ScenariosNewRoute;
  ScenariosIndexRoute: typeof ScenariosIndexRoute;
}

const ScenariosRouteRouteChildren: ScenariosRouteRouteChildren = {
  ScenariosScenarioIdRoute: ScenariosScenarioIdRoute,
  ScenariosNewRoute: ScenariosNewRoute,
  ScenariosIndexRoute: ScenariosIndexRoute,
};

const ScenariosRouteRouteWithChildren = ScenariosRouteRoute._addFileChildren(
  ScenariosRouteRouteChildren,
);

interface SettingsRouteRouteChildren {
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute;
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute;
  SettingsGeneralRoute: typeof SettingsGeneralRoute;
  SettingsInstructionsRoute: typeof SettingsInstructionsRoute;
  SettingsMarkdownEditorRoute: typeof SettingsMarkdownEditorRoute;
  SettingsProvidersRoute: typeof SettingsProvidersRoute;
  SettingsStorageRoute: typeof SettingsStorageRoute;
  SettingsUsageRoute: typeof SettingsUsageRoute;
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAdvancedRoute: SettingsAdvancedRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsInstructionsRoute: SettingsInstructionsRoute,
  SettingsMarkdownEditorRoute: SettingsMarkdownEditorRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsStorageRoute: SettingsStorageRoute,
  SettingsUsageRoute: SettingsUsageRoute,
};

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScenariosRouteRoute: ScenariosRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
